"""Command-line interface for CSPM."""
from __future__ import annotations

import argparse
import html
import json
import sys

from . import TOOL_NAME, TOOL_VERSION
from .core import SEVERITY_ORDER, load_config, scan, summarize

_SEV_COLORS = {
    "CRITICAL": "#7c1d1d",
    "HIGH": "#b91c1c",
    "MEDIUM": "#b45309",
    "LOW": "#1d4ed8",
    "INFO": "#374151",
}


def _render_table(findings, summary) -> str:
    lines = []
    lines.append(f"{TOOL_NAME} {TOOL_VERSION} — cloud security posture")
    lines.append("=" * 60)
    sev = summary["by_severity"]
    lines.append(
        "Summary: {total} findings  (CRIT {CRITICAL} | HIGH {HIGH} | "
        "MED {MEDIUM} | LOW {LOW} | INFO {INFO})".format(
            total=summary["total"], **sev
        )
    )
    lines.append("=" * 60)
    if not findings:
        lines.append("No findings. Posture looks clean for the supplied export.")
        return "\n".join(lines)
    width = max((len(f.severity) for f in findings), default=8)
    for f in findings:
        lines.append(f"[{f.severity:<{width}}] {f.check_id}  {f.resource}")
        lines.append(f"    {f.title}")
        lines.append(f"    {f.detail}")
        lines.append(f"    -> {f.recommendation}")
    return "\n".join(lines)


def _render_json(findings, summary) -> str:
    return json.dumps(
        {
            "tool": TOOL_NAME,
            "version": TOOL_VERSION,
            "summary": summary,
            "findings": [f.to_dict() for f in findings],
        },
        indent=2,
    )


def _render_html(findings, summary) -> str:
    sev = summary["by_severity"]
    rows = []
    for f in findings:
        color = _SEV_COLORS.get(f.severity, "#374151")
        rows.append(
            "<tr>"
            f'<td><span class="badge" style="background:{color}">{html.escape(f.severity)}</span></td>'
            f"<td><code>{html.escape(f.check_id)}</code></td>"
            f"<td><code>{html.escape(f.resource)}</code></td>"
            f"<td><strong>{html.escape(f.title)}</strong><br>"
            f'<span class="detail">{html.escape(f.detail)}</span><br>'
            f'<span class="rec">→ {html.escape(f.recommendation)}</span></td>'
            "</tr>"
        )
    rows_html = "\n".join(rows) or (
        '<tr><td colspan="4" class="detail">No findings — posture looks clean.</td></tr>'
    )
    cards = "".join(
        f'<div class="card" style="border-color:{_SEV_COLORS[s]}">'
        f'<div class="num" style="color:{_SEV_COLORS[s]}">{sev[s]}</div>'
        f'<div class="lbl">{s}</div></div>'
        for s in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{TOOL_NAME} report</title>
<style>
* {{ box-sizing: border-box; }}
body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0;
  background: #0f172a; color: #e2e8f0; }}
.wrap {{ max-width: 1000px; margin: 0 auto; padding: 24px; }}
h1 {{ font-size: 20px; margin: 0 0 4px; }}
.sub {{ color: #94a3b8; font-size: 13px; margin-bottom: 20px; }}
.cards {{ display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }}
.card {{ background: #1e293b; border-left: 4px solid; border-radius: 8px;
  padding: 14px 18px; min-width: 90px; }}
.num {{ font-size: 26px; font-weight: 700; }}
.lbl {{ font-size: 11px; letter-spacing: .06em; color: #94a3b8; }}
table {{ width: 100%; border-collapse: collapse; background: #1e293b;
  border-radius: 8px; overflow: hidden; }}
th, td {{ text-align: left; padding: 10px 12px; vertical-align: top;
  border-bottom: 1px solid #334155; font-size: 13px; }}
th {{ background: #0b1220; color: #94a3b8; text-transform: uppercase;
  font-size: 11px; letter-spacing: .05em; }}
.badge {{ color: #fff; padding: 2px 8px; border-radius: 999px;
  font-size: 11px; font-weight: 700; }}
code {{ color: #7dd3fc; }}
.detail {{ color: #cbd5e1; }}
.rec {{ color: #86efac; }}
footer {{ color: #64748b; font-size: 12px; margin-top: 16px; }}
</style></head><body><div class="wrap">
<h1>{TOOL_NAME} — Cloud Security Posture Report</h1>
<div class="sub">{summary['total']} findings · worst severity: {summary['worst']} · generated by {TOOL_NAME} {TOOL_VERSION}</div>
<div class="cards">{cards}</div>
<table><thead><tr><th>Severity</th><th>Check</th><th>Resource</th><th>Finding</th></tr></thead>
<tbody>
{rows_html}
</tbody></table>
<footer>Defensive posture analysis on configuration you own. No live cloud calls were made.</footer>
</div></body></html>
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=TOOL_NAME,
        description="Cloud security posture from a config export (defensive triage).",
    )
    parser.add_argument("--version", action="version",
                        version=f"{TOOL_NAME} {TOOL_VERSION}")
    sub = parser.add_subparsers(dest="command")

    scan_p = sub.add_parser("scan", help="Scan a config export for posture findings.")
    scan_p.add_argument("config", help="Path to the JSON config export.")
    scan_p.add_argument("--format", choices=["table", "json", "html"],
                        default="table", help="Output format.")
    scan_p.add_argument("-o", "--output",
                        help="Write report to this file instead of stdout.")
    scan_p.add_argument("--fail-on", choices=list(SEVERITY_ORDER),
                        default="LOW",
                        help="Minimum severity that causes a non-zero exit.")
    return parser


def main(argv=None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command != "scan":
        parser.print_help()
        return 2

    try:
        config = load_config(args.config)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: could not read config export: {exc}", file=sys.stderr)
        return 2

    findings = scan(config)
    summary = summarize(findings)

    if args.format == "json":
        report = _render_json(findings, summary)
    elif args.format == "html":
        report = _render_html(findings, summary)
    else:
        report = _render_table(findings, summary)

    if args.output:
        try:
            with open(args.output, "w", encoding="utf-8") as fh:
                fh.write(report)
        except OSError as exc:
            print(f"error: could not write output: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {args.format} report to {args.output}", file=sys.stderr)
    else:
        print(report)

    threshold = SEVERITY_ORDER[args.fail_on]
    if any(SEVERITY_ORDER.get(f.severity, 0) >= threshold for f in findings):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
